some updates

diff --git a/create_script b/create_script
--- a/create_script
+++ b/create_script
@@ -6,23 +6,15 @@
 
 # Is there an argument?
 if [[ ! $1 ]]; then
-	echo "Missing argument"
+	echo "Missing argument" >&2
 	exit 1
 fi
-
-scriptname="$1"
-bindir="${HOME}/bin"
-filename="${bindir}/${scriptname}"
-
-if [[ -e $filename ]]; then
-	echo "File ${filename} already exists"
-	exit 1
+declare open_editor=""
+if [[ $# -eq 1 ]]; then
+	open_editor="true"
 fi
 
-if type "$scriptname" > /dev/null 2>&1; then
-	echo "There is already a command with name ${scriptname}"
-	exit 1
-fi
+declare -r bindir="${HOME}/bin"
 
 # Check if bin directory exists
 if [[ ! -d $bindir ]]; then
@@ -35,19 +27,43 @@ if [[ ! -d $bindir ]]; then
 	fi
 fi
 
-# Create a script with some lines:
-echo '#!/bin/bash' > "$filename"
-echo '' >> "$filename"
-echo '# Description:' >> "$filename"
-echo '# Author: slisandr' >> "$filename"
+while [[ $1 ]]; do
+	scriptname="$1"
+	filename="${bindir}/${scriptname}"
 
-# Add executable permission
-chmod u+x "$filename"
+	if [[ -e $filename ]]; then
+		echo "File ${filename} already exists" >&2
+		shift
+		continue
+	fi
+
+	if type "$scriptname" > /dev/null 2>&1; then
+		echo "There is already a command with name ${scriptname}" >&2
+		shift
+		continue
+	fi
+
+	# Create a script with some lines:
+	echo '#!/bin/bash' > "$filename"
+	echo '' >> "$filename"
+	echo '# Author: slisandr' >> "$filename"
+	echo '# Description:' >> "$filename"
+
+	# Add executable permission
+	chmod u+x "$filename"
+
+	shift
+done
+
+
 # Open with editor
-if [[ $EDITOR ]]; then
-	$EDITOR "$filename"
-else
-	echo "Script created; not starting editor because \$EDITOR is not set"
+if [[ $open_editor ]]; then
+	echo "Opening"
+	if [[ $EDITOR ]]; then
+		$EDITOR "$filename"
+	else
+		echo "Script created; not starting editor because \$EDITOR is not set"
+	fi
 fi
 
 exit 0
diff --git a/tn b/tn
--- a/tn
+++ b/tn
@@ -4,20 +4,36 @@
 # Author: slisandr
 
 # get the date
-date=$(date)
+declare -r date=$(date)
 
 # get the topic
-topic="$1"
+declare -r topic="$1"
+
+# determine where to save our notes
+declare notesdir="${HOME}"
+[[ $NOTESDIR ]] && notesdir="${NOTESDIR}"
+
+if [[ ! -d $notesdir ]]; then
+	mkdir "${notesdir}" 2> /dev/null || { echo "Cannot make directory ${notesdir}" 1>&2; exit 1; }
+fi
 
 # filename to write to
-filename="${HOME}/${topic}notes.txt"
+filename="${notesdir}/${topic}notes.txt"
+
+# Does file exist? If not, create it
+if [[ ! -f $filename ]]; then
+	touch "${filename}" 2> /dev/null || { echo "Cannot create file ${filename}" 1>&2; exit 1; }
+fi
+
+# Is file writable?
+[[ -w $filename ]] || { echo "${filename} is not writable" 1>&2; exit 1; }
 
 # Ask user for input
 read -p "Your note: " note
 
 if [[ $note ]]; then
 	echo "$date: $note" >> "$filename"
-	echo "Note '$note' saved to $filename."
+	echo "Note '$note' saved to $filename." 1>&2
 else
 	echo "No input; note wasn't saved." 1>&2
 fi
